### ISSUE TITLE
Firewall rules with port ranges always recreated

### ISSUE THREAD

**Issue by jdmulloy** [squat/terraform-provider-vultr#38]
It seems like there is an unmarshalling error here. Any firewall rules with a port range are recreated on every plan/apply.

# Terraform code
```
resource "vultr_firewall_rule" "home_zabbix" {
  firewall_group_id = "${vultr_firewall_group.default.id}"
  cidr_block = "${var.home_ipv4}/32"
  protocol = "tcp"
  from_port = "10050"
  to_port = "10051"
}

resource "vultr_firewall_rule" "home_mosh" {
  firewall_group_id = "${vultr_firewall_group.default.id}"
  cidr_block = "${var.home_ipv4}/32"
  protocol = "tcp"
  from_port = "60000"
  to_port = "61000"
}
```
# Output
```
-/+ vultr_firewall_rule.home_mosh (new resource required)
      id:                "fe129394/23" => <computed> (forces new resource)
      action:            "accept" => <computed>
      cidr_block:        "192.168.1.1/32" => "192.168.1.1/32"
      direction:         "in" => <computed>
      firewall_group_id: "fe129394" => "fe129394"
      from_port:         "0" => "60000" (forces new resource)
      protocol:          "tcp" => "tcp"
      to_port:           "0" => "61000" (forces new resource)

-/+ vultr_firewall_rule.home_zabbix (new resource required)
      id:                "fe129394/22" => <computed> (forces new resource)
      action:            "accept" => <computed>
      cidr_block:        "192.168.1.1/32" => "192.168.1.1/32"
      direction:         "in" => <computed>
      firewall_group_id: "fe129394" => "fe129394"
      from_port:         "0" => "10050" (forces new resource)
      protocol:          "tcp" => "tcp"
      to_port:           "0" => "10051" (forces new resource)
```

**Comment by squat** [comment]
@jdmulloy thanks for finding this bug. It looks like the Vultr API is returning firewall rule port ranges as `x - y`, when I could have sworn it used to be `x:y`. 8e57c4406906bf299e6414671c4fa06b5204c0a2 should fix this bug. Please let me know if you still see the problem and re-open this issue.

**Comment by jdmulloy** [comment]
Thanks @squat,

Unfortunately now I'm getting an error. Although it may be a separate bug?
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

vultr_firewall_group.default: Refreshing state... (ID: fe129394)
vultr_firewall_rule.ipv6_submission: Refreshing state... (ID: fe129394/6)
vultr_firewall_rule.ipv6_https: Refreshing state... (ID: fe129394/17)
vultr_firewall_rule.nagios-vps-vu-se-1a_ssh_ipv6: Refreshing state... (ID: fe129394/10)
vultr_firewall_rule.nagios-vps-vu-se-1a_ssh_ipv4: Refreshing state... (ID: fe129394/14)
vultr_firewall_rule.ipv4_submission: Refreshing state... (ID: fe129394/3)
vultr_firewall_rule.ipv6_icmp: Refreshing state... (ID: fe129394/18)
vultr_firewall_rule.home_zabbix: Refreshing state... (ID: fe129394/22)
vultr_firewall_rule.nagios-vps-vu-nj-1a_ssh_ipv4: Refreshing state... (ID: fe129394/13)
vultr_firewall_rule.ipv4_https: Refreshing state... (ID: fe129394/11)
vultr_firewall_rule.home_ssh: Refreshing state... (ID: fe129394/19)
vultr_firewall_rule.ipv4_smtp: Refreshing state... (ID: fe129394/2)
vultr_firewall_rule.nagios-vps-vu-nj-1a_ssh_ipv6: Refreshing state... (ID: fe129394/15)
vultr_firewall_rule.ipv6_http: Refreshing state... (ID: fe129394/21)
vultr_firewall_rule.ipv4_http: Refreshing state... (ID: fe129394/1)
vultr_firewall_rule.ipv4_icmp: Refreshing state... (ID: fe129394/20)
vultr_firewall_rule.ipv6_ntp: Refreshing state... (ID: fe129394/7)
vultr_firewall_rule.home_mosh: Refreshing state... (ID: fe129394/23)
vultr_firewall_rule.nagios-vps-vu-fl-1a_ssh_ipv4: Refreshing state... (ID: fe129394/12)
vultr_firewall_rule.ipv4_ntp: Refreshing state... (ID: fe129394/5)
vultr_firewall_rule.nagios-vps-vu-fl-1a_ssh_ipv6: Refreshing state... (ID: fe129394/9)
vultr_firewall_rule.ipv6_smtp: Refreshing state... (ID: fe129394/8)

Error: Error refreshing state: 2 error(s) occurred:

* vultr_firewall_rule.ipv6_icmp: 1 error(s) occurred:

* vultr_firewall_rule.ipv6_icmp: vultr_firewall_rule.ipv6_icmp: Error parsing port range for firewall rule (fe129394/18): strconv.Atoi: parsing "": invalid syntax
* vultr_firewall_rule.ipv4_icmp: 1 error(s) occurred:

* vultr_firewall_rule.ipv4_icmp: vultr_firewall_rule.ipv4_icmp: Error parsing port range for firewall rule (fe129394/20): strconv.Atoi: parsing "": invalid syntax
```

This is the relevant terraform code.
```
resource "vultr_firewall_rule" "ipv4_icmp" {
  firewall_group_id = "${vultr_firewall_group.default.id}"
  cidr_block = "0.0.0.0/0"
  protocol = "icmp"
}

resource "vultr_firewall_rule" "ipv6_icmp" {
  firewall_group_id = "${vultr_firewall_group.default.id}"
  cidr_block = "${var.ipv6_global_cidr}"
  protocol = "icmp"
}
```

**Comment by squat** [comment]
Ah yes, this last commit introduced a regression for parsing empty port ranges. I’ll fix it and add some new tests for this case. Thanks for the feedback!

**Comment by squat** [comment]
@jdmulloy please give the latest master another shot. I fixed the regression and added tests to catch this in the future.

**Comment by jdmulloy** [comment]
I'm still getting an error. Digging into it more this is the partial json I'm getting for the icmp rule, so the fix doesn't detect this because it's "-" as a string. I'll work on a PR.

```
"20": {
        "rulenumber": 20,
        "action": "accept",
        "protocol": "icmp",
        "port": "-",
        "subnet": "0.0.0.0",
        "subnet_size": 0
    }
```
